### PR TITLE
Fix #2009: Add lists to plugins to support lists in editor

### LINKED ISSUE #2009: Tinymce bullist en numlist don't work anymore
Since the release of the new tinymce editor we need a special plugin for the numlist en bullist, lists. This has to be added to the tiny-init.js of the new version.

### PR DESCRIPTION
**Pull request by DorienD**
### Description

Fix #2009

Add tinymce plugin `lists` to support numlist and bullist to new tinymce editor 4.9.3

### CODE REVIEW

**Comment by DorienD** [comment]
@mworrell @ddeboer could we add this to a 0.46.1 release?

**Comment by mworrell** [comment]
Can you (temporarily) switch to an older tinyMCE version?  Then you don't need to wait for a release.

**Comment by mworrell** [comment]
@ddeboer Do we want to make a patch release?  The 0.47 is planned for coming Monday.

**Comment by ddeboer** [comment]
Nope, let’s just stick to 0.47.

**Comment by mworrell** [comment]
ok, closing this issue.

@DorienD thanks for the fix!

**Comment by DorienD** [comment]
When will 0.47 be tagged? Since all our production sites will be affected if we release 0.46.

**Comment by ddeboer** [comment]
https://github.com/zotonic/zotonic/milestones

**Pull request merged**
