### PR TITLE
Add a lock to the pivot table to prevent race conditions

### PR DESCRIPTION
**Pull request by mmzeeman**
### Add a pivot table lock to prevent race conditions

The table `rsc_pivot_queue` will be locked in row share exclusive mode to prevent race
conditions when updating a resource, or adding edges to the resource.

Removed the catch clause. It looks like it was there to prevent race condition errors from propagating. These kind of errors can no longer happen because of the lock.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by mmzeeman** [comment]
I think `share row exclusive mode` is the right mode for this. See: https://www.postgresql.org/docs/9.5/sql-lock.html

**Comment by mworrell** [comment]
merged, also in master.

**Comment by mmzeeman** [comment]
Nice.. I'm wondering if there are other places which need this treatment.

On master we probably also want to upgrade `epgsql` at some point.

**Comment by mworrell** [comment]
On master we use epgsql 3.4.0, don't know what changed in the 4.3.0.

**Comment by mmzeeman** [comment]
The changelog mentions small changes, new error messages, in the connect call. They now have typespecs, that could help with finding problems.

**Pull request merged**
