### PR TITLE
core: Move mod_acl_simple_roles out of the core into separate repo

### LINKED ISSUE #1131: Deprecate adminonly and simple_acl in favour of acl_user_groups
There are now too many ACL options (especially for newcomers to the framework) to choose from. 

What about deprecating adminonly and simple_acl or at least strongly recommending to use acl_user_groups? Or does anyone still see good use cases for the older two ACL modules?

### PR DESCRIPTION
**Pull request by ddeboer**
Moved to https://github.com/zotonic/mod_acl_simple_roles.

Fix #1131.

Does everyone agree on removing mod_acl_simple_roles from the 0.x branch, too?

### CODE REVIEW

**Comment by ddeboer** [comment]
@mmzeeman Do you agree if we apply this change to 0.x, too? It means that mod_acl_simple_roles no longer comes as a Zotonic core module so you’ll need to clone it from its separate repo.

**Comment by mmzeeman** [comment]
Fine by me.

I'm going to look at moving to the groups acl after the summer.

**Comment by mworrell** [comment]
I am also ok with moving it out - we just need to communicate clearly and have this module available om the zmr

**Comment by ddeboer** [comment]
Also cherry-picked into 0.x.

**Pull request merged**
