### PR TITLE
added -noshell flag to zotonic-debug to make it launchd compatible (Fixes zotonic/zotonic#1031)

### PR DESCRIPTION
**Pull request by aseidlitz**
See issue zotonic/zotonic#1031 for details

### CODE REVIEW

**Comment by mworrell** [comment]
I was wondering if the Launchd shouldn't be started with the *start* argument instead of *debug*.  The *start* argument will launch a detached beam process.

**Comment by aseidlitz** [comment]
Yes, processes managed by Launchd must not daemonize (fork, detach, etc.) Here's the reference: https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-104738

**Comment by arjan** [comment]
I don't think we should pass `-noshell` to `zotonic debug`, as that defeats its purpose. The idea is to run Zotonic in the foreground for debugging purposes, while providing an erlang REPL. `-noshell` effectively disables the REPL...

A better idea would be to modify the `zotonic start` command to add a `--keep-in-foreground` (`-k`) option.

**Comment by CyBeRoni** [comment]
A non-debug foreground option would also be very useful for Linux with systemd and Solaris SMF.

**Comment by arjan** [comment]
PR's welcome :)

**Comment by mmzeeman** [comment]
Or should we go for something like this? https://github.com/ShoreTel-Inc/erld/wiki

**Comment by CyBeRoni** [comment]
If you are using a model where the server process forks, then those points are absolutely what should be followed (especially the 'don't return until the service has started successfully' part). 

But the more modern service starters (Darwin Launchd, Linux SystemD, Solaris SMF, Ubuntu Upstart) typically prefer to have daemons *not* fork, instead disconnecting stdin/out/err for them (and redirecting the latter two to a log file, often) and allowing for better process supervision.

**Comment by mmzeeman** [comment]
Should we wait for the third edition of "Advanced Programming in the UNIX environment" ;-)

**Comment by CyBeRoni** [comment]
I have an alternative patch for this, see #1080.

**Comment by mworrell** [comment]
Fixed with #1080

**Pull request closed without merging**
