### PR TITLE
Run xref on Travis CI

### LINKED ISSUE #1316: Run xref on Travis CI
Rebar config was added in #1315.

### PR DESCRIPTION
**Pull request by ddeboer**
Fix #1316.

### CODE REVIEW

**Comment by ddeboer** [comment]
@mworrell Please fix the partial mod_survey merge to solve the missing function call. 😉

**Comment by mworrell** [comment]
That scomp can be removed.

**Comment by mworrell** [comment]
We now have the following error:

```
===> Warning: erlydtl_parser:return_error/2 is unused local function (Xref)
```

This is inside the generated Yecc parser.
Either we find a way to disable checks for certain modules or merge this after merging the new template compiler.

**Comment by ddeboer** [comment]
> ```
> ===> Warning: erlydtl_parser:return_error/2 is unused local function (Xref)`
> ```

@mworrell This one is fixed, some new ones popped up after merging in the new template compiler. Feel like fixing those? :wink:

**Comment by mworrell** [comment]
Merged, good work @ddeboer

**Pull request merged**
