### PR TITLE
Add 19.0 as CI target. New mochiweb

### LINKED ISSUE #1323: OTP 19.0 compatibility
We need to test for Erlang/OTP 19.0.

Things to do for master:

- [x] Upgrade gen_smtp
- [x] Upgrade jobs
- [x] Upgrade template_compiler
- [x] Upgrade filezcache
- [x] Upgrade lager to 3.2.1
- [x] Upgrade parse_trans to 3.0
- [x] Upgrade erlware_commons to 0.21.0
- [x] Fix [qdate](https://github.com/mworrell/qdate/blob/master/rebar.config#L3)'s `rebar.config`
- [x] Change type #{} to map() ( #{} is from now on the empty map)
- [x] SSL ciphers problem (upgrade mochiweb)
- [x] Add 19.0 as a CI target
- [x] Remove deprecation warnings
- [ ] Switch gen_smtp to the hex package

Things to do for 0.x:

- [x] Upgrade gen_smtp (to 0.11.0)
- [x] Upgrade jobs
- [x] Upgrade filezcache
- [x] Upgrade lager to 3.2.1
- [x] Upgrade parse_trans to 3.0
- [x] Upgrade erlware_commons to 0.21.0
- [x] SSL ciphers problem (upgrade mochiweb)
- [x] Add 19.0 as a CI target

### PR DESCRIPTION
**Pull request by mworrell**
Fixes #1323

### CODE REVIEW

**Comment by ddeboer** [comment]
Restarted the build: it’s green now. :wink:

**Comment by mworrell** [comment]
We might want to set the top-19 target to be allowed to fail. Till 19 is available on Travis.

**Comment by ddeboer** [comment]
Sure, we can do that if it starts failing. :) For now it's green. 






On Sat, Jun 25, 2016 at 2:18 PM +0200, "Marc Worrell" <notifications@github.com> wrote:










We might want to set the top-19 target to be allowed to fail. Till 19 is available on Travis.

**Comment by mworrell** [comment]
Nice, then OTP-19 was added to Travis

**Pull request merged**
