### PR TITLE
Add block around language options

### PR DESCRIPTION
**Pull request by loetie**
Add block around language options so it is possible to overwrite/extend this template in modules/sites with inherit possibilities.

- [ ] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
I am a bit curious, why a block around the whole template?  Is that more useful for you than just overwriting the template?

**Comment by loetie** [comment]
The idea is that it is possible to add something after the current code without overriding the current code (inherit) so if the original template is updated those still automatically work. 

Example:
`{% overrules%}

{% block language_options %}

{% inherit %}

{% button
    text=_"Auto translate this page"
    class="btn--secondary"
    postback={auto_translate id=id}
%}

{% endblock %}`

**Comment by mworrell** [comment]
Completely valid reason 👍

**Comment by mworrell** [comment]
Also merged into master via 1a80978cb23afe6d0ac38b583ab0b408e0ebd2ae

**Pull request merged**
