### PR TITLE
Upgrade epgsql to version 3.0.0

### PR DESCRIPTION
**Pull request by frkarl**
Changed epgsql to version 3.0 and renamed all calls to pgsql to epgsql.

### CODE REVIEW

**Comment by frkarl** [comment]
https://github.com/zotonic/zotonic/issues/969

**Comment by arjan** [comment]
Nice one, thanks! I'm gonna try it out and will get back to this one.

**Comment by mworrell** [comment]
Great work :+1: from me for a merge (after @arjan's test run)

**Comment by mworrell** [comment]
It passed all my local tests.
Merged it.

Thanks @frkarl !

**Pull request merged**
