### PR TITLE
Adds pt-BR translation

### PR DESCRIPTION
**Pull request by williamthome**
### Description

Adds pt-BR translation.
It also fixes `lanuage` typo in `.po` files and sublanguage selection in the admin panel.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Review by vkatsuba — CHANGES_REQUESTED** [review]
Please revert changes in `*.po` files and keep changes only in `*.tpl` files? You see, all `*.po` files is generated/updated automatically by [crowdin](https://crowdin.com/project/zotonic).

**Review by vkatsuba — COMMENTED** [review]
Also I suppose it make sense to divide PR to few PR's where:
1 - `Adds pt-BR translation`
2 - `translation: Fix typo`

**Comment by mworrell** [comment]
Indeed, the <code>.zotonic.po files are generated by crowdin using the zotonic.pot file.

We should check the misc .po files in l10n, as at least some of their translations are also in the zotonic.pot file.

**Comment by williamthome** [comment]
Forgive me for not seeing that the translations are generated on crowding.
I left this message to Marc on crowding shortly after opening the PR:

> "Hi, Marc! How are you?
> I created a PR and turned it into a draft after seeing this message "Disabled: translation is done via Crowdin at [https://crowdin.com/project/zotonic"](https://crowdin.com/project/zotonic%22) in the `mergepot` file. 
> How to add a pt-BR (Brazilian Portuguese) translation here?
> Link to the PR: https://github.com/zotonic/zotonic/pull/2972"

**Comment by mworrell** [comment]
Hi @williamthome, just answered your question on Crowdin.

We can add pt-BR at crowdin and let them do a first machine translation.

I am wondering, how different is pt-BR from pt?
This, as we need to maintain both translations.

**Comment by williamthome** [comment]
There are significant differences.
Check this issue https://github.com/ipfs-shipyard/i18n/issues/7
e.g. In BR `Save` is `Salvar` and PT `Guardar`. For BR, `Guardar` is something like `Store`.
But I understand it would be one more language to maintain.

**Comment by mworrell** [comment]
Considering those differences I will enable pt-BR

**Comment by mworrell** [comment]
Something is wrong with the 'pt-br' machine translation, we get a 'pt' file at the moment.

Have to check this and how a fix affects other translations.

**Comment by mworrell** [comment]
I've configured crowdin to add a pt-br file.

This is machine translated using Google Translate (DeepL didn't have pt-BR).

If you rebase on master then you will have the new files and crowdin.yml

**Comment by williamthome** [comment]
Thanks, @mworrell!
I will split this PR into others as recommended by @vkatsuba.

**Pull request closed without merging**
