### PR TITLE
New template compiler

### PR DESCRIPTION
**Pull request by mworrell**
**Work in progress**

Integrating the new template compiler at https://github.com/zotonic/template_compiler

To do:

- [x] Add include sudo/anondo support
- [x] Integrate with z_filewatcher
- [x] Move erlydtl datetime module to new module
- [x] Remove erlydtl sub-directory
- [x] Remove specific erlydtl tests (they are now in the template_compiler repo)
- [x] Change all calls to erlydtl modules
- [x] Check calls to z_template.erl
- [x] Add debugging support to template_compiler
- [x] Add new filter tests (to be added as separate issue)

### CODE REVIEW

**Comment by ddeboer** [comment]
Cool! 

You put this on the 1.0 milestone, so am I correct in assuming that it’s no prerequisite for (e.g.) #1076?

**Comment by mworrell** [comment]
@ddeboer The template_compiler uses `maps` and `merl`. So it is tied to the Erlang 18. I think we should expedite the 1.0 release and after fixing the template_compiler add the cowboy integration (and most pressing issues for the 1.0)

**Comment by ddeboer** [comment]
And can we do #1113 separately or has it now become dependent on 1.0 as well?

**Comment by mworrell** [comment]
#1113 can be done independently.

**Comment by mworrell** [comment]
This is now ready to be squashed and merged.

Added issue #1303 for the extra filter (and scomp) tests.

**Comment by mworrell** [comment]
@ddeboer and @arjan can you run some sites with this branch to see if there are any obvious problems?

**Comment by mworrell** [comment]
Almost ready: need to add sudo/anondo support for the include tags.

**Comment by mworrell** [comment]
Added support for `sudo`, `anondo` and `z_language` context variables.

They can be supplied in *include*, *for*, *with* and value statements like `{{ .... with z_language='en' }}`

**Comment by mworrell** [comment]
@ddeboer @arjan @mmzeeman Please check this branch with a sample project. It is now ready to be merged.

I didn't do any performance checks - any performance degradations should be solved later.

**Comment by ddeboer** [comment]
Awesome work, @mworrell! 👊

**Comment by mmzeeman** [comment]
Indeed, it works very nice... Wow.

**Pull request merged**
