### PR TITLE
core: fix problem with identifiers in templates

### LINKED ISSUE #1288: 500 Error on admin page
Hi, someone can help to figure out what is happening with my installation?

This happen only when try `http://zotonic.dev:8000/admin`

FYR:
OS: El Capitan
Erlang r18

```shell
14:22:18.859 [info] http://zotonic.dev:8000                        - running
:0: function identifier/1 undefined
14:22:26.295 [error] Error compiling template: <<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">> ({'EXIT',{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}})
14:22:26.296 [error] Error rendering template: <<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_admin/templates/admin_logon.tpl">> ({error,{template_compile_error,<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>,{'EXIT',{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}}}})
14:22:26.296 [error] Error in process <0.773.0> on node 'zotonic001@LORENZO-HERNANDEZ' with exit value:
{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}
```
Screenshot:
screen shot 2016-05-22 at 2 27 53 pm

### PR DESCRIPTION
**Pull request by willemdj**
Fixes #1288.

### CODE REVIEW

**Comment by ddeboer** [comment]
Verifying this locally, hold on.

**Comment by ddeboer** [comment]
Still throws the same error as described in #1288 for me.

**Comment by willemdj** [comment]
Yes, I think so.

When I started zotonic before this fix (without any configuration, just plain zotonic), I got to the login page without problems. After login I got to the Zotonic Sites page, with nothing there (which probably makes sense). When I clicked on the "Toggle tracing" option 2 error messages appeared: one like described in #1288, and another one:

```erlang
** dbg got EXIT - terminating: {trace_handler_crashed,
                                {{badrecord,wm_log_data},
                                 [{z_tracer,tracefun,2,
                                   [{file,
                                     "/home/willem/zotonic/_build/default/lib/zotonic/src/support/z_tracer.erl"},
                                    {line,67}]},
                                  {dbg,handle_traces,4,
                                   [{file,"dbg.erl"},{line,819}]},
                                  {dbg,tracer_loop,2,
                                   [{file,"dbg.erl"},{line,783}]}]}}
```

I looked at the erlydtl_compiler module and realized that it contained an error. This caused compilation of templates with an {{ #id }} tag to fail. I fixed that, and verified that these templates now compile. I also restarted zotonic, and noticed that the error related to the identifier no longer occurred. (The error related to the tracing is still there.)

**Comment by willemdj** [comment]
Apologies, I just noticed that there is another place in erlydtl_compiler where something similar happens. I'll need to fix that as well (and do a proper check to ensure that this is all...).

**Comment by willemdj** [comment]
I fixed that second thing, tried to ensure that I am now complete and did some extra tests - the template _logon_login_support.tpl now also compiles, judging from the original error message that did not work before.

**Comment by ddeboer** [comment]
Yes, this fixes the bug! :balloon:

**Pull request merged**
