### PR TITLE
Close open db connections on a 'too may connections' error.

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Issue #1469 

This is a workaround for the problem where a database connection can not be made due to many other sites having open database connections.

If a _too many connections_ error is detected, then we close (almost all) open database connections held by db workers that are not in use.
### Checklist
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by ddeboer** [comment]
:+1:

**Comment by mworrell** [comment]
And we need to test it against a real database....

**Comment by ddeboer** [comment]
We have one on Travis. Do you want a test for it?

**Comment by mworrell** [comment]
I was first thinking of a local test, by reconfiguring a local PostgreSQL server with a low connection limit.

**Comment by mworrell** [comment]
I did some extra testing with a couple of sites and only 15 allowed db connections.
It now works well (after restructuring the site startup and fixing some smaller issues with the db connection process)

**Comment by mworrell** [comment]
@ddeboer @arjan can you test this with your own dev env?

**Comment by mworrell** [comment]
@ddeboer ok to merge this (and cherry-pick into 0.x)?

**Comment by mworrell** [comment]
Merged this into the 0.x https://github.com/zotonic/zotonic/commit/8a747af1c4af352d713ade6721cb933e86188578

**Pull request merged**
