### PR TITLE
Add scripts to do 'z:m()' from the command line; wait for zotonic to be started.

### PR DESCRIPTION
**Pull request by CyBeRoni**
This helps automated deployments; they could be used like zotonic wait && zotonic make.

### CODE REVIEW

**Comment by ddeboer** [comment]
Do we need `zotonic-make` if we already have `zotonic-compile`? I prefer to have a separate `zotonic-flush` instead: after all, make = compile + flush.

**Comment by CyBeRoni** [comment]
zotonic-compile runs a function directly in an erlang interpreter, while this zotonic-make tells a running zotonic to do it using rpc. 

I'd prefer to have the flush built-in myself but I could modify it to support an argument and call z:c() in absence of such a thing, which doesn't flush.

**Comment by arjan** [comment]
Why not collapse all of this into one command?
Refactor `zotonic compile` so that it follows the following logic:

 * zotonic not running: perform the "current" `zotonic compile` function
 * zotonic running: perform "wait" and then the RPC call.

I see the case for a separate `zotonic flush` call though.

**Comment by CyBeRoni** [comment]
> Why not collapse all of this into one command?

I'm not personally the largest fan of do-it-all commands. I usually prefer to string smaller things together when automating. You know, the unix way.

**Comment by CyBeRoni** [comment]
That said, the zotonic-make that's in there now could also be renamed zotonic-rpc and just be an interface to call functions directly. Then I would use something like zotonic wait && zotonic rpc "z m"

**Comment by arjan** [comment]
Yeah, that makes more sense to me. Having both a `zotonic compile` and `zotonic make` command makes things very confusing.

**Comment by CyBeRoni** [comment]
David: 0.15? I need this literally two weeks ago.

**Comment by CyBeRoni** [comment]
Changed to make a generic "zotonic rpc" command.

**Comment by ddeboer** [comment]
> David: 0.15? I need this literally two weeks ago.

I understand, but we’re still discussing the best course of action here while the 0.14 release branch was created yesterday.

**Comment by CyBeRoni** [comment]
This PR was made two weeks ago.

**Comment by arjan** [comment]
This looks good, only thing that's missing is documentation.
Please add these two new commands [here](https://github.com/zotonic/zotonic/blob/master/doc%2Fref%2Fcli%2Findex.rst), then I'll merge it.

**Comment by CyBeRoni** [comment]
Added.

**Comment by ddeboer** [comment]
Cool, please squash commits!

**Comment by arjan** [comment]
I'll do it

**Comment by CyBeRoni** [comment]
Don't worry, I just squashed the shit out of this.

**Comment by arjan** [comment]
It's merged now to master but I dont know to which release branch to merge it to.
@ddeboer can you explain?

**Comment by CyBeRoni** [comment]
David tells me 0.13.x will be replaced next week with 0.14 so that will do for me.

**Comment by ddeboer** [comment]
Cherry-picked into 0.14.0. Just because I’m in a good mood. :wink:

**Comment by arjan** [comment]
yay :-)

**Pull request closed without merging**
