### PR TITLE
Automatically publish managed ACL rules

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Comment by ddeboer** [comment]
@mworrell As far as I can see, publishing the rules (often) shouldn’t cause any trouble.

**Comment by mworrell** [comment]
Yes, it is ok to publish - though with many content groups we have seen that it can take a bit of time (but that is a different problem which we can tackle separately)

**Comment by ddeboer** [comment]
In that case, feel free to merge this.

**Comment by mworrell** [comment]
Thanks!

**Pull request merged**
