### PR TITLE
Remove jQuery migrate

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Change some JS code so that jQuery migrate can de removed.

### Checklist

- [x] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
@mmzeeman please add any other cleanup you need 👍

**Comment by mmzeeman** [comment]
Didn't find any other things. I was wondering if we should give a warning in the release notes about the removal. It could be that older sites are affected by the removal.

**Comment by mworrell** [comment]
Yes, we should add a warning in the release notes.

**Comment by mworrell** [comment]
Added a preliminary 0.56 release note to the docs.

**Pull request merged**
