### PR TITLE
core: Use ceil/1 BIF

### PR DESCRIPTION
**Pull request by ddeboer**
### Description

Fix "Warning: ambiguous call of overridden auto-imported BIF ceil/1"

Please describe here what the PR does.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by ddeboer** [comment]
This (of course) only works on Erlang/OTP 20, and we currently have 19 as the minimum version.

**Comment by mworrell** [comment]
How far is cowboy with demanding at least OTP 20?

**Comment by ddeboer** [comment]
Cowboy currently only requires 19. Not sure whether they have a reason to switch to 20.

**Comment by mworrell** [comment]
I propose to fix this with a bigger update removing all warnings of this kind.

**Pull request closed without merging**
