### PR TITLE
mod_email_dkim: Add DKIM signing of outgoing emails

### PR DESCRIPTION
**Pull request by arjan**
cc @mworrell @ddeboer

### CODE REVIEW

**Comment by ddeboer** [comment]
Very cool! Perhaps @CyBeRoni can have a look as well, from his ops standpoint.

**Comment by arjan** [comment]
Makes sense. The admin page looks like this:

image

**Comment by CyBeRoni** [comment]
What's RSI?

**Comment by arjan** [comment]
Oops, that's RSA, obviously.

The DKIM selector [is already configurable](https://github.com/zotonic/zotonic/pull/1260/commits/855d2778eda6b5d56836eb1fe902ea6319fe5ed4#diff-47d44beefebabb587c0c7c2d25410c4eR41)

**Comment by CyBeRoni** [comment]
Alrighty.

**Comment by mworrell** [comment]
Good work 👍

**Comment by mworrell** [comment]
The keys must be present as files?
Or can we also store them in the database?

**Comment by arjan** [comment]
We could also store them in the database. But sysops like files better, I think ;)

**Comment by mworrell** [comment]
This builds on 73199483e7f1a8c3fc64d11acd1803b24880e79c ?

**Comment by arjan** [comment]
Yes, and is merge already (b6db7e2c622918082be1e1954542dab99d1bd411)

**Comment by mworrell** [comment]
Good!

**Comment by ddeboer** [comment]
Again, please use the ‘merge’ functionality and do *not* merge through separate commits!

**Pull request closed without merging**
