### PR TITLE
Re-create custom pivot table when definition changes

### PR DESCRIPTION
**Pull request by Dirklectisch**
The schema of a pivot table often evolves over time. Changing a pivot table currently means you have manually delete the table from all environments which is quite a hassle. I propose that we just delete and re-init the table when the definition changes.

### CODE REVIEW

**Comment by mworrell** [comment]
I am not sure about the equality check for the columns. As one comes from the spec, and one comes from the database. There could be a (small) textual change between them, and still have the same spec. Such a textual difference would then result in the new pivot table being rebuild on every module init.

**Comment by Dirklectisch** [comment]
You will lose the table if you start renaming columns in it, that's correct. But in normal scenarios the column names in the db and the spec should match.

**Comment by mworrell** [comment]
I was thinking of the *Type* of the columns. Matching on the names is a good idea and stable.

**Comment by Dirklectisch** [comment]
@mworrell Changed the comparison so that it only compares column names.

**Comment by ddeboer** [comment]
LGTM to now. 

@Dirklectisch Can you add a note to [the docs](http://docs.zotonic.com/en/0.x/cookbook/custom-pivot.html) explaining that pivot changes will now re-create the table, losing all (albeit transient) data currently in it?

**Comment by Dirklectisch** [comment]
@ddeboer Docs updated

**Comment by ddeboer** [comment]
Thanks!

**Pull request merged**
