### PR TITLE
Fix links to documentation stuff

### PR DESCRIPTION
**Pull request by vkatsuba**
### Description

Issue: N/A

The link https://docs.zotonic.com/docs/latest/developer-guide/search.html#query-model-arguments is not working.

### Checklist

- [x] documentation updated

### CODE REVIEW

**Comment by mworrell** [comment]
Thanks @vkatsuba!

I see you also edited the .po file, that one is generated by crowdin via the .pot file.  Can you push again without the .po file?  Then i'll generate a new .pot, which crowdin will pick up automatically from the master branch.

**Comment by vkatsuba** [comment]
Yep, good point, I was doing the same for .po at crowdin - https://github.com/zotonic/zotonic/pull/2932. Will update.

**Comment by vkatsuba** [comment]
@mworrell done.

**Comment by mworrell** [comment]
And merged, thanks! 👍

**Pull request merged**
