### PR TITLE
Build docs on Travis

### LINKED ISSUE #1128: Build documentation on Travis
So we can test whether there are any invalid references etc.

### PR DESCRIPTION
**Pull request by ddeboer**
Fix #1128.

### CODE REVIEW

**Comment by mworrell** [comment]
Haha, then we also need to fix the docs ;)

**Comment by ddeboer** [comment]
Working on that :construction_worker:

**Comment by ddeboer** [comment]
This is now green.

**Comment by ddeboer** [comment]
Please merge if you’re okay with this so we can continue working on the docs.

**Pull request merged**
