### PR TITLE
Remove trailing whitespaces from .tpl and .erl

### PR DESCRIPTION
**Pull request by ddeboer**
As defined in .editorconfig.

### CODE REVIEW

**Comment by arjan** [comment]
Nice!
Instead of cherrypicking this onto 0.x it is probably easier to rerun the script and do a separate commit there. (or didnt you use a script? :))

**Comment by ddeboer** [comment]
Yep, I already pushed a separate whitespace trim to 0.x.

**Comment by ddeboer** [comment]
Not sure why the build is suddenly failing with `Warning: erlydtl_parser:return_error/2 is unused local function (Xref)`, though.

**Comment by arjan** [comment]
Weird. Maybe @mworrell knows.

**Comment by ddeboer** [comment]
Oops, my mistake: I accidentally committed `erlydtl_compiler.erl` along with the rest of the files.

**Comment by mworrell** [comment]
I hope this whitespace change won't give me merge conflicts with the rather huge cowboy changes I am making.... Am afraid it will, as it touches almost every single file.

**Comment by arjan** [comment]
You can always rebase to resolve the conflicts..

**Comment by ddeboer** [comment]
> I hope this whitespace change won't give me merge conflicts with the rather huge cowboy changes I am making

No worries, I merged master into the cowboy branch here: https://github.com/zotonic/zotonic/pull/1355

Merge instead of rebase because it’s now a PR with commits from multiple people.

**Comment by mworrell** [comment]
@ddeboer it gave me 9 merge conflicts with the outstanding work I had here, bit less than I worried as I am changing all controllers and a lot of other routines.

**Pull request merged**
