### PR TITLE
Refactor the show_media filter.

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Cause of this refactor was an issue reported by @karlsson regarding the alignment of body media.

Upon closer inspection it is clear that the `_body_media.tpl` and the `show_media` filter are a bit outdated. 

 * Alignment classes are not compatible with bootstrap
 * No mediaclass handling
 * Configuration key for sizes
 * Special handling of oembed content
 * An (almost) similar template in the skel directory

This merge request tries to clean up the filter and template so that it becomes more flexible and fits better in bootstrap sites. 

### Checklist

- [x] decide on place of default large/middle/small mediaclass
- [x] documentation updated
- [ ] tests added
- [x] no BC breaks (there are BC breaks, they are documented with the `show_media` filter)

### CODE REVIEW

**Comment by mworrell** [comment]
@DorienD can you check if this `_body_media.tpl` is ok for your normal usage in bootstrap sites?

**Comment by mworrell** [comment]
@ddeboer  ready to be merged, can you have a look?

screen shot 2017-03-07 at 11 46 21

**Comment by DorienD** [comment]
_body_media.tpl looks good to me.

**Comment by karlsson** [comment]
Beautiful! It works fine in Firefox.

2017-03-07 11:47 GMT+01:00 Marc Worrell <notifications@github.com>:

**Comment by mworrell** [comment]
Merging, as @DorienD says ok to the tpl and @karlsson tested it with various browsers.

**Pull request merged**
