### PR TITLE
core: add sanitization on the contents of uploaded SVG files.

### PR DESCRIPTION
**Pull request by mworrell**
This adds sanitization of SVG files and a place to add sanitization of other uploaded files.

See issue #1265

### CODE REVIEW

**Comment by mworrell** [comment]
@ddeboer If this is merged, maybe issue a 0.16.1 ?

**Comment by ddeboer** [comment]
Agreed. Please add a release note for 0.16.1 in this PR explaining the change.

**Comment by arjan** [comment]
Nice huh, the github mention bot! :-)

**Comment by ddeboer** [comment]
>  the github mention bot!

Yeah, the bots are haunting you?: 😨

**Comment by mworrell** [comment]
Just checked the ImageMagick issue, the policy.xml file should solve all issues (together with our content sniffing/checking), so I don't think we need an intermediate 0.16.1 release.

All ok?

**Comment by ddeboer** [comment]
:+1:

**Pull request merged**
