### PR TITLE
core: fix a problem where compilation of templates generates random atoms

### LINKED ISSUE #1673: ErlyDTL compiler creates too many atoms
One of our servers just crashed with `no more index entries in atom_tab (max=1048576)`. As it turns out, the number of atom entries is very high on other servers as well. @mworrell reports nearly 1M entries on one of his servers.

The culprit seems to be [this line](https://github.com/zotonic/zotonic/blob/0.x/src/erlydtl/erlydtl_compiler.erl#L158) in erlydtl_compiler.

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Fix #1673

This replaces dynamic atom generation with predictable enumerated atoms, such limiting the number of different atoms to be generated.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
@ddeboer please check this against your projects. It works well with the projects (and admin) I tested against.

**Comment by mmzeeman** [comment]
Indeed, this is better, but this can only be a problem when templates are (re)compiled a lot. Is this because mod_development was running in production?

**Comment by mworrell** [comment]
The 0.x is a bit conservative when it recompiles, like when modules are switched on and off, or when translations are loaded. 

The original assumption (in 2009) was that there were not a lot of templates, so that this leak would be small enough to disregard.

**Comment by ddeboer** [comment]
We’re currently testing this branch on our test server. Will report here if we find any problems.

**Comment by mmzeeman** [comment]
The branch worked for us... Didn't look at the atoms used before and after though.

**Pull request merged**
