### PR TITLE
Login format check

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Fix #3449

Modified version of change request by @heiheshang 

### Checklist

- [ ] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
@heiheshang can you check if this works for you?  You will need to set the `mqtt_username_format_0x` key in your zotonic.config file.

**Comment by mworrell** [comment]
@heiheshang ping 😃

**Comment by heiheshang** [comment]
@mworrell  pong

**Comment by mworrell** [comment]
Still needed?

**Comment by heiheshang** [comment]
yes, I still have devices with old settings

**Pull request merged**
