### PR TITLE
Fix a problem where SMTP would not fall back to plain text on port 25

### LINKED ISSUE #3686: SMTP - SSL shared cipher
## `Zotonic` version
Latest master

I have several websites relaying email thru an email server, and it has worked great for several months. A few days ago I noticed that mail is no longer being sent, so I checked the logs in Zotonic and the mail server.

The mail server reports the same error each time Zotonic attempts to relay a message: `error:0A0000C1:SSL routines:no shared cipher`

Nothing has changed on the mail server, and have verified everything is good using the [internet.nl](https://internet.nl/test-mail/) test site, so I am wondering if something may have recently changed in Zotonic related to SMTP? 

I can setup a test VM and do the same test to a Zotonic instance setup to receive mail, but just wanted to make an inquiry first, in case there was something changed recently that is quick and simple to diagnose...

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Fix #3686

Remove the TLS options and optionally reset to port 25.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by seannaswell** [comment]
Unfortunately it appears non-TLS is not attempted. 

Mail server log:
`2024-02-28 01:03:34.485 [90556] TLS error on connection Ci=90556 from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 (SSL_accept): error:0A000410:SSL routines::sslv3 alert handshake failure
2024-02-28 01:03:34.485 [90556] SMTP connection Ci=90556 from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 D=0.440s closed by EOF
2024-02-28 01:03:34.485 [90556] no MAIL in SMTP connection from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 Ci=90556 D=0.440s C=EHLO,STARTTLS`

Zotonic debug:
`2024-02-28 01:03:28 INFO  site=seannaswell  user_id=1 <0.5237.0> [z_email_server:send_blocking_smtp/6:1095] ▸ text="Sending email" relay=10.0.1.14 recipient=test@test.domain port=25 message_id=yxz1w3ftygqcss02kufk in=zotonic_core
2024-02-28 01:03:34 ERROR  site=seannaswell  user_id=1 <0.5237.0> [z_email_server:spawned_email_sender_loop/13:945] ▸ text="Error sending email" result=error relay=10.0.1.14 recipient=test@test.domain reason=send message={error,closed} in=zotonic_core host=10.0.1.14 failure_type=network_failure`

**Comment by seannaswell** [comment]
Unfortunately it appears non-TLS is not attempted. 

Mail server log:
`2024-02-28 01:03:34.485 [90556] TLS error on connection Ci=90556 from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 (SSL_accept): error:0A000410:SSL routines::sslv3 alert handshake failure
2024-02-28 01:03:34.485 [90556] SMTP connection Ci=90556 from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 D=0.440s closed by EOF
2024-02-28 01:03:34.485 [90556] no MAIL in SMTP connection from (seannaswell.com) [10.0.1.10]:62203 I=[10.0.1.14]:25 Ci=90556 D=0.440s C=EHLO,STARTTLS`

Zotonic debug:
`2024-02-28 01:03:28 INFO  site=seannaswell  user_id=1 <0.5237.0> [z_email_server:send_blocking_smtp/6:1095] ▸ text="Sending email" relay=10.0.1.14 recipient=test@test.domain port=25 message_id=yxz1w3ftygqcss02kufk in=zotonic_core
2024-02-28 01:03:34 ERROR  site=seannaswell  user_id=1 <0.5237.0> [z_email_server:spawned_email_sender_loop/13:945] ▸ text="Error sending email" result=error relay=10.0.1.14 recipient=test@test.domain reason=send message={error,closed} in=zotonic_core host=10.0.1.14 failure_type=network_failure`

**Comment by mworrell** [comment]
@seannaswell  Thanks, seems we get a `network_failure` error here.  I have changed the code a bit to also handle this case. Could you try again with the `3686-smtp-fallback` branch?

**Comment by seannaswell** [comment]
> Could you try again with the `3686-smtp-fallback` branch?

Done. All good! The first try fails, and the re-try without TLS succeeds.

```
2024-02-28 13:13:08 INFO  site=seannaswell  user_id=1 <0.3253.0> [z_email_server:send_blocking_smtp/6:1100] ▸
 text="Sending email" relay=10.0.1.14 recipient=test@test.domain port=25 message_id=2c52sbyobgu3vsquotvi in=zotonic_core
2024-02-28 13:13:14 NOTICE  site=seannaswell  user_id=1 <0.3253.0> [z_email_server:send_blocking_no_tls/5:1145] ▸
 text="SMTP closed or timeout error, retrying without TLS" relay=10.0.1.14 recipient=test@test.domain port=25 in=zotonic_core
2024-02-28 13:13:23 NOTICE  site=seannaswell  user_id=1 <0.3253.0> [z_email_server:spawned_email_sender_loop/13:1032] ▸ 
text="Sent email" result=ok recipient=test@test.domain message="check data host accepted" in=zotonic_core
```

**Comment by seannaswell** [comment]
Is the same thing possible for any user defined port?  

That would be helpful for people forwarding to local mail servers, and to alleviate potential issues sending mail in the case of SSL errors... 

Worst case, if using a host such as the big G, the connection won't be accepted.

**Comment by mworrell** [comment]
Thanks! Then I'll merge this. We can look at the ports another time.

**Comment by mworrell** [comment]
We use the config `site.smtp_relay_port` for the plain text as well.
So only if the config is not set, then we will fallback to the plaintext port 25.

**Pull request merged**
