### PR TITLE
Fix erlang_localtime and qdate_localtime name clashes

### LINKED ISSUE #2253: Name clashes in code paths
There are a couple of beam files with the same name on a fresh install of 0.x. 

I'm not experiencing any issues though.

```
** /zotonic/deps/qdate_localtime/ebin/localtime_dst.beam hides /zotonic/deps/erlang_localtime/ebin/localtime_dst.beam
** /zotonic/deps/qdate_localtime/ebin/ibuild.beam hides /zotonic/deps/erlang_localtime/ebin/ibuild.beam
** /zotonic/deps/qdate_localtime/ebin/localtime.beam hides /zotonic/deps/erlang_localtime/ebin/localtime.beam
```

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Fix #2253

Remove dep to erlang_localtime, only keep qdate_localtime.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
@rl-king can you give this a test drive?  It should fix the name clash problem.

**Comment by rl-king** [comment]
Ok nice, I'll work from this branch today and report back

**Comment by rl-king** [comment]
Compilation crashes because this file is missing https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_l10n/src/models/m_l10n.erl#L37 

It seems to be the only reference to `erlang_localtime`. So updating the path should fix it.

**Comment by mworrell** [comment]
Should be ok now

**Comment by rl-king** [comment]
Compiled without the warnings and used it all day working on two different sites without any issues

**Comment by mworrell** [comment]
Thanks for testing @rl-king.  The xref also doesn't show any problems with these modules, so I am merging.

**Pull request merged**
