### PR TITLE
jsmin

### LINKED ISSUE #1823: Minification of javascript and css
Our clients are calling us constantly that we should minify our javascript and css files. They do this because they use the Google Pagespeed insights tool and look at the "tips" google gives them.

Personally I hate this tool, because it doesn't even measure the speed of the page, but all clients use it.

This is what it looks like when you run the pagespeed insight tool on zotonic.com

screen shot 2017-10-12 at 08 28 29

From the looks of it things look really bad.

When you use a tool which really measures the speed of your page things look very different.

screen shot 2017-10-12 at 08 31 54

Some clients think they get a fast site and a higher pagerank by fixing all the tips mentioned by the Google pagespeed insights tool. How are you dealing with this? Sometimes I think we should just minify the javascript and css in the lib tags to prevent them from calling us.

### PR DESCRIPTION
**Pull request by mmzeeman**
### Description

Fix #1823

This PR introduces a new dispatch rule in order to automatically minify javascript and css files. It is possible to turn on automatic minification for the entire site. The PR is backward compatible, the minification is turned off by default.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mmzeeman** [comment]
TODO, a new z_stdlib version has to be added.

**Comment by ddeboer** [comment]
@mmzeeman Is this now ready (apart from the merge conflict)?

**Comment by mmzeeman** [comment]
Yes.. I've enabled this version this morning on our beta test server and turned on automatic minification as a last check.

**Comment by ddeboer** [comment]
Can you resolve the merge conflict so we can merge this?

**Comment by mmzeeman** [comment]
Done

**Pull request merged**
