### PR TITLE
Fix xref issues

### PR DESCRIPTION
**Pull request by gomoripeti**
This is a naive attempt to address some of the warnings emitted by xref.

### CODE REVIEW

**Comment by mmzeeman** [comment]
Hi Peter,

Thanks for the PR with all these embarrassing typo's and fixes. 👍 

@marc Do you use `translation_scan2` for a closed project? Or is it something new?

BTW Is it possible to create a xref command we can run more often? It looks very useful.

**Comment by arjan** [comment]
Looks great, @gomoripeti! And embarrassing indeed.. we need better code coverage :-s
@mmzeeman I think the `rebar3 xref` command is what you're looking for. We should add it to our CI pipeline.

**Comment by arjan** [comment]
I suspect `translation_scan2` was a leftover and got added by accident.

**Comment by mworrell** [comment]
`translation_scan2` is indeed an accidental leftover.

**Comment by mworrell** [comment]
👍 for merging.

Indeed good to add xref to our CI pipeline.

**Comment by mworrell** [comment]
I will rebase #1300 after this has been merged.

**Comment by mworrell** [comment]
Thanks!

**Comment by ddeboer** [comment]
Great, thanks @gomoripeti! 🌟

**Comment by gomoripeti** [comment]
wow, thanks for looking at this and merging it so fast.
and xref is already added to CI, I can hardly follow the pace zotonic is moving forward with :)

**Comment by mworrell** [comment]
Thanks, and you timed the patch perfectly, on the day that @ddeboer, @arjan and I were at the same location.

**Pull request merged**
