### PR TITLE
docker: Create lite Zotonic container

### LINKED ISSUE #1295: Create slim Docker image
* Create slim image beside the current full one: the slim image should not include PostgreSQL.
* Split development (`build-essential` etc.) and production images
* Add Dockerfile to 0.x branch, too.

@CyBeRoni Any ideas how to create proper production images that don’t include build tools? Of course, to create a deployable container, we do need the tools.

### PR DESCRIPTION
**Pull request by ddeboer**
Fix #1295.

### CODE REVIEW

**Comment by mworrell** [comment]
@kaos Andreas, can you have a look, as our in-house Docker expert? :)

**Comment by kaos** [comment]
Looks good. 👍 for a "lite" runtime image where the DB has been moved out. That's the right move before using this in production.

**Comment by ddeboer** [comment]
That's exactly the idea, @kaos!

Please don't merge yet as this is not completely finished. I'm still looking for a way to have multiple Dockerfiles but not clutter up the repo's root directory. We can define multiple Dockerfiles on Docker Hub, but if they are in a subdirectory their context is only that directory, not the whole repo.

**Comment by ddeboer** [comment]
Added docs. @kaos and others, please review. I renamed the old `zotonic/zotonic` Docker image to `zotonic/zotonic-full` and removed Postgres from the `zotonic/zotonic` (slim) one.

**Comment by kaos** [comment]
👍

**Pull request merged**
