### PR TITLE
core: Add facets property to search_result

### LINKED ISSUE #1447: Extend search_result with facets
Add a `facets` property to the `#search_result{}` record. While probably not used in the Zotonic core (facets are quite hard to do in Postgres) it will be very useful to return facets from `observe_search_query/2` observers that query [Elasticsearch](https://github.com/zotonic/zotonic/milestone/3), Solr and the like.

### PR DESCRIPTION
**Pull request by ddeboer**
### Description

Fix #1447.

### Checklist

- [x] no BC breaks

### CODE REVIEW

**Comment by ddeboer** [comment]
They are opaque indeed. The only thing this PR does is add a place for search modules to return the facets with the search results. The search module (or individual site) templates then decide how to process those facets to (e.g.) show a list of filters.

**Comment by mworrell** [comment]
Ok with that for now, later we can establish a standard format.

**Comment by ddeboer** [comment]
Alright, so can be merged?

**Comment by mworrell** [comment]
Also merged into master at c734c6c

**Pull request merged**
