### PR TITLE
Increase resource URI length

### LINKED ISSUE #1156: Make rsc.uri column bigger
Any objections to this? It’s currently 250 chars, but when working with linked data we sometimes encounter longer URIs.

### PR DESCRIPTION
**Pull request by ddeboer**
Fix #1156. This of course works only for newly created sites, but that seems sufficient for now.

See also http://stackoverflow.com/a/417184.

### CODE REVIEW

**Comment by mworrell** [comment]
2K is still (just) below the max key size in postgresql B-tree indices. And as most entries will have much shorter urls (or none) I think this is ok.

If many entries will have a longer keys then we might want to add an index using a (shal1) checksum of the uris.

**Comment by mworrell** [comment]
:+1: to merge into 0.13 and master

**Comment by mworrell** [comment]
BTW talking about resource uris. We do sanitize the incoming uris, maybe we also want to normalize them?  (Thinking of upper/lower case, escapes, etc)

**Comment by ddeboer** [comment]
Cherry-picked as 5993714ba870621fbecaf7a6bc31529c4821bcf4 into master.

**Pull request merged**
