### PR TITLE
TinyMCE russian translation additions

### PR DESCRIPTION
**Pull request by imagency**
Changes to TinyMCE module to provide russian translation into editor panel.

### CODE REVIEW

**Comment by mworrell** [comment]
Thanks!

**Comment by mworrell** [comment]
BTW are you using 0.11.x or 0.12.x ?

**Comment by imagency** [comment]
I am using 0.12.4 now.

**Comment by mworrell** [comment]
Ok, then I merge your changes into 0.12.x as well

**Comment by mworrell** [comment]
Cherry-picked it into the 0.12.x branch.

**Pull request merged**
