### PR TITLE
[WIP] escripts

### PR DESCRIPTION
**Pull request by tantemelki**
Convert Zotonic's bash scripts to escripts

### CODE REVIEW

**Comment by mworrell** [comment]
Hi @tantemelki, a quick heads up for your work. Looks like it is going into a good direction.  Maybe also check `z_path.erl` and `zotonic_compile.erl`, we have been making some changes there that might also be relevant to your work.

**Comment by mworrell** [comment]
Might 1.1, but realistically I think this will be in the 1.0

**Comment by ddeboer** [comment]
Hey @tantemelki, welcome to Zotonic! Great changes!

I’m seeing quite some duplicate commits from our master branch, where the commit hash we have on master differs from your fork, tantemelki/zotonic. This makes it hard to differentiate between your changes to the escripts and other, unrelated changes by other people.

Could you please split your changes from the unrelated changes ? If you’re not sure how to do so, please let us know so we can help out.

**Comment by tantemelki** [comment]
@ddeboer thanks for the advice. I'm going to do the changes mentioned and update my PR

**Comment by tantemelki** [comment]
@ddeboer thanks for the advice. I'm going to do the changes mentioned and update my PR

**Comment by arjan** [comment]
This is currently broken, unfortunately.
To continue I would suggest using `rebar escriptize` to package all Erlang modules which are needed for the zotonic shell commands (basically, all `zotonic_cmd_*` modules) into a single binary.

The new OTP structure makes this easy; I would put everything in the `zotonic_launcher` OTP application.

Furthermore, please also check that it works on OTP version 19; some functions that you use now (`string:length` being one of them) are not defined in that version.

**Comment by mworrell** [comment]
Re OTP version 19: Cowboy2 will be OTP 20 only, so it is ok to only be compatible with OTP 20.

The `zotonic_launcher` app is indeed the prime location for these scripts, then they can also be packaged with other OTP applications that include `zotonic_launcher` as a dependency.

I like the `zotonic_cmd_*` module approach!

**Comment by tantemelki** [comment]
Hello @mworrell @arjan,

I moved everything to the zotonic_launcher application. I used rebar escriptize to generate an escript binary, but  not quite sure how to go about including that in the escript I wrote.

 Also, like @ddeboer said, I really don't know how to go about splitting my work from unrelated changes

**Comment by mworrell** [comment]
Hei @tantemelki, I was just wondering if this was ready for a merge.  Did you close this merge request for a rebase?

**Comment by tantemelki** [comment]
@mworrell yes. I will summit a new PR when I've done a rebase and others

**Comment by mworrell** [comment]
@tantemelki Great news, thanks!

**Pull request closed without merging**
