### PR TITLE
WIP: Add support for dmy formatted dates when updating models

### PR DESCRIPTION
**Pull request by linuss**

### CODE REVIEW

**Comment by ddeboer** [comment]
Our use case here is to show dates in the admin in a localised format (7-1-2019 instead of 2019-01-07), and this change seemed necessary.

**Comment by mworrell** [comment]
I propose to restructure this.  Scheduling it preemptively for  the 0.48.

Agreeing with to re-check the date-picker options.

**Comment by mworrell** [comment]
Moving to 0.49, as we have still pending reviews.

**Comment by mworrell** [comment]
@ddeboer any movement on this?

**Comment by mworrell** [comment]
Checking if there is another solution to this.

**Comment by mworrell** [comment]
Superseded by #2098

**Pull request closed without merging**
