### PR TITLE
core: add timer on pw checks against timing attacks for finding valid usernames

### PR DESCRIPTION
**Pull request by mworrell**
### Description

There is a timing difference between checking a password for valid usernames and invalid usernames.

The timing difference can be used to find valid usernames.

This change adds a timer around the pw check to make all pw checks about 300msec.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
Discussion is if this should have a base of 300 msec.

We can also measure the time needed for a typical password hash check, and then use that as a base for the timer.

On my dev machine a password hash takes around 350 msec:

```
(zotonic@PoToi)6> timer:tc(fun() -> erlpass:hash(<<"jdhjsadhidhihihhfs">>) end).
{351085,
 <<"$2a$12$2vty8V2M.g3iP1.4CtWFVutCOrlyNytqcOyxRklcCbxl//7oGiQ.2">>}
```

**Comment by mmzeeman** [comment]
Performance varies indeed. My M1 MacBook takes 230 msec.

```erlang 
(zotonic@Tukkal)3> timer:tc(fun() -> erlpass:hash(<<"jdhjsadhidhihihhfs">>) end).
{232047,
 <<"$2a$12$us0N8kuE58n7GHFLrnD2au02rsrTlh3wuvrMlfwwq.7goK3MRTnhu">>}

```

**Review by mmzeeman — APPROVED** [review]
Looks like a good default pw-check duration. Our dedicated server is about 5 years old.

**Comment by mworrell** [comment]
My dev machine is 4 years old, 2,2 GHz 6-Core Intel Core i7.

**Pull request merged**
