### PR TITLE
 CORS in rest api

### PR DESCRIPTION
**Pull request by ghosthamlet**
add CORS header in rest api header, enable in site config file

### CODE REVIEW

**Comment by mworrell** [comment]
@mmzeeman can you have a look at this one please?

**Comment by mworrell** [comment]
We are checking if this shouldn't be part of webzmachine, as there are also CORS request headers.

Url for some documentation/reading http://www.html5rocks.com/en/tutorials/cors/

Adding @arjan to the discussion.

**Comment by arjan** [comment]
Sorry for the very late reply. This patch looks reasonable to me like this.

Two comments:
* Rename the option to `service_api_cors`
* It would be nice to have the `{service_api_cors, true}` option documented in [site-anatomy.rst](https://github.com/zotonic/zotonic/blob/5b3bdad831a88031badcb53fc847fe8c1a3f10a8/doc/manuals/site-anatomy.rst site-anatomy.rst), so it is clear which headers are set by activating this.

* And maybe for later: make each header configurable (allowed hosts, request methods, etc)

**Comment by ghosthamlet** [comment]
i have renamed the option, added document to site-anatomy.rst,  but your link is broken. 
the other header configuration (allowed hosts etc) i think we can just expose to user with original header name and value, as there are many options there.    many users may use the service_api_cors only, but few advanced users may set the others, they know what they do, so i think it aslo not very necessary to validate the others value in set_cors_header.

**Comment by arjan** [comment]
@ghosthamlet I finally got around to it becase I needed it for my own project. I did some small changes but overall it looked fine. Thanks for the contribution!

**Pull request closed without merging**
