### PR TITLE
Remove user agent class support

### LINKED ISSUE #1347: What should we do with z_user_agent sniffing?
Recently I tried to update the device classifier databases of our user agent classifier. What I found was that the project we based our classifier on has stopped and (sort of) merged with Apache.

See: https://issues.apache.org/jira/browse/DMAP-11

This means that we either have to move our device map to use the device data from apache or maybe stop using the user agent sniffer.

See also: 

http://devicemap-vm.apache.org/data/snapshot/

and 

https://github.com/zotonic/ua_classifier/issues/3

### PR DESCRIPTION
**Pull request by mworrell**
Fixes #1347 

This removes the `ua_classifier` and support for user-agent specific templates.

To do:

 - [x] Documentation
 - [x] Testing

### CODE REVIEW

**Comment by mworrell** [comment]
@arjan @ddeboer ready to be merged, can you test drive it?

**Comment by mmzeeman** [comment]
BTW: This looks like a nice erlang application which does ua agent identification.

https://github.com/SiftLogic/uaparser

It recognizes the recent safari as:

```
[{browser,[{name,<<"safari">>},{family,<<"safari">>},{manufacturer,<<"apple">>},{type,<<"web_browser">>},{renderer,<<"webkit">>},{version,<<"9.1.1">>},{version_details,[{major,9},{minor,1},{patch,1}]}]},
 {os,[{name,<<"mac os x">>},{family,<<"mac_os_x">>},{manufacturer,<<"apple">>},{type,<<"computer">>},{version,<<"10_11_5">>},{version_details,[{major,10},{minor,11},{patch,5}]}]}]
```

**Comment by ddeboer** [comment]
@mmzeeman The current idea is just to throw out User Agent identification, as it can and should be solved on the CSS instead (media queries and the like). Do you have a user case for User Agent identification in Erlang?

@mworrell Will try to find some time for testing.

**Comment by mmzeeman** [comment]
@ddeboer Indeed, for template selection browser classification is not needed anymore. But for informational purposes it is sometimes needed to have browser identification. Think about support forms, statistics, ugly hacks (sometimes needed). My current use case is to make an informational page of all logged in users of an account to a supervisor. This page needs some browser information, like "Safari on iPod", "Firefox on windows 8".

**Comment by mworrell** [comment]
Checked with @ArthurClemens, going to merge this.

**Comment by ddeboer** [comment]
@mworrell Thanks!

**Pull request merged**
