### PR TITLE
mod_acl_user_groups: added support for collaboration groups. Issue #1099

### PR DESCRIPTION
**Pull request by mworrell**
This adds support for collaboration groups to the `mod_acl_user_groups`, issue #1099 

Collaboration groups are simple user groups with the following properties:

 1. All content belongs to the collaboration group (*content_group_id* is the collaboration group)
 2. There is one set of ACL rules for all collaboration groups, which defines which content can be viewed.
 3. A collaboration group has members and managers. These are defined by connections from the group to the users.
 4. Managers can add/remove members. 
 5. Members and managers are allowed to view/create content within the collaboration group.

It is also possible to add specific ACL rules between user groups and collaboration groups. This to publish (or hide) selected collaboration groups.

### CODE REVIEW

**Comment by mworrell** [comment]
@ddeboer Please check this

**Comment by ddeboer** [comment]
On my vanilla site this throws:

```erlang
11:22:13.560 [info] Site started: vanilla (<0.13216.0>)
11:22:13.792 [error] [vanilla] z_db error {error,error,<<"25P02">>,<<"current transaction is aborted, commands ignored until end of transaction block">>,[]} in query "select id from rsc where name = $1" with [<<"acl_user_group_managers">>]
11:22:13.793 [error] [vanilla] Error starting module mod_acl_user_groups, Schema initialization error:
{'EXIT',{{case_clause,{rollback,{{error,{error,error,<<"25P02">>,<<"current transaction is aborted, commands ignored until end of transaction block">>,[]}},[{z_db,'-q1/4-fun-1-',5,[{file,"src/db/z_db.erl"},{line,311}]},{timer,tc,2,[{file,"timer.erl"},{line,179}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,206}]},{m_rsc,name_lookup,2,[{file,"src/models/m_rsc.erl"},{line,700}]},{m_rsc,p,3,[{file,"src/models/m_rsc.erl"},{line,454}]},{m_rsc,is_a,3,[{file,"src/models/m_rsc.erl"},{line,758}]},{mod_acl_user_groups,manage_schema,2,[{file,"modules/mod_acl_user_groups/mod_acl_user_groups.erl"},{line,542}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"src/db/z_db.erl"},{line,141}]}]}}},[{z_module_manager,manage_schema,4,[{file,"src/support/z_module_manager.erl"},{line,829}]},{z_module_manager,'-start_child/6-fun-1-',6,[{file,"src/support/z_module_manager.erl"},{line,637}]}]}}
11:22:13.793 [error] [vanilla] Module mod_acl_user_groups start error {error,{schema_init,{'EXIT',{{case_clause,{rollback,{{error,{error,error,<<"25P02">>,<<"current transaction is aborted, commands ignored until end of transaction block">>,[]}},[{z_db,'-q1/4-fun-1-',5,[{file,"src/db/z_db.erl"},{line,311}]},{timer,tc,2,[{file,"timer.erl"},{line,179}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,206}]},{m_rsc,name_lookup,2,[{file,"src/models/m_rsc.erl"},{line,700}]},{m_rsc,p,3,[{file,"src/models/m_rsc.erl"},{line,454}]},{m_rsc,is_a,3,[{file,"src/models/m_rsc.erl"},{line,758}]},{mod_acl_user_groups,manage_schema,2,[{file,"modules/mod_acl_user_groups/mod_acl_user_groups.erl"},{line,542}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"src/db/z_db.erl"},{line,141}]}]}}},[{z_module_manager,manage_schema,4,[{file,"src/support/z_module_manager.erl"},{line,829}]},{z_module_manager,'-start_child/6-fun-1-',6,[{file,"src/support/z_module_manager.erl"},{line,637}]}]}}}}
```

**Comment by mworrell** [comment]
Interesting error, will try to reproduce it.

**Comment by ddeboer** [comment]
Pretty cool. Still requires documentation. :wink:

**Comment by arjan** [comment]
:+1: That would be very helpful... I probably have a use case for this in the near future  :)

**Comment by ddeboer** [comment]
We’ll do documentation separately: #1240.

**Comment by mworrell** [comment]
Squashed the commits.  Everybody ok to merge after Travis give a green light?

**Comment by mworrell** [comment]
Green light, merging...

**Pull request merged**
