### PR TITLE
core: Return error tuple instead of throwing exception

### LINKED ISSUE #1641: Remove exceptions
In the resource routines some exceptions are thrown.

There are a couple of problems with that:

 1. This is against the principle of non-local returns in Erlang
 2. Code becomes harder to reason with
 3. The *throw* looks different after a `z_db:transaction/2` call, as it is rethrown but with the original stack trace tagged on

I propose to replace most throws with simple `{error, …}` return values.

### PR DESCRIPTION
**Pull request by ddeboer**
### Description

Fix #1641.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by ddeboer** [comment]
Now green. Please check whether I forgot any throws.

**Comment by mworrell** [comment]
Looks good to me!

The remaining throws in `z_db:q` (and friends) we can remove in a separate issue.

**Comment by ddeboer** [comment]
See #1703 for `z_db`.

**Comment by ddeboer** [comment]
Added a section in the Upgrading doc chapter.

**Pull request merged**
