### PR TITLE
Dialyzer 3/3 (passes)

### PR DESCRIPTION
**Pull request by mworrell**
### Description

More dialyzer fixes.

### Checklist

- [ ] documentation updated
- [ ] tests added
- [x] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
The last remaining warning is about a `{error, econnrefused}` returned by `epgsql_connect` but not mentioned in its type definition.

We might want to suppress this warning and get a type-spec fix merged into epgsql.

**Comment by mworrell** [comment]
@ddeboer We got green on the Dialyzer build!

https://travis-ci.org/zotonic/zotonic/builds/566139318

Shall we enable Dialyzer in the OTP 19.3 step?
Then we have something like:

```yaml
matrix:
  include:
    - otp_release: 21.3
      env: ELVIS=true
    - otp_release: 20.3
      env: BUILD_DOCS=true
    - otp_release: 19.3
      env: DIALYZER=true
  fast_finish: true
```

Then we have something "special" in all three builds.

/cc @mmzeeman

**Comment by mworrell** [comment]
The new travis config passes the CI testing:

https://travis-ci.org/zotonic/zotonic/builds/566200600

**Comment by ddeboer** [comment]
Nice! Well done. 👍

**Pull request merged**
