### PR TITLE
Cotonic

### PR DESCRIPTION
**Pull request by mworrell**
### Description

Integrate Cotonic

This replaces the transport, MQTT and other UI parts of Zotonic with Cotonic.

This is a *major* overhaul

 - [x] Add Cotonic checkout to mod_base
 - [x] Remove old MQTT modules & interfaces
 - [x] Integrate `mqtt_sessions` app
 - [x] Move `z_mqtt_acl` into new mqtt_sessions runtime module
 - [x] Add `render_state` field to `#context{}` replacing the z_script buffers
 - [x] Remove session and page session (will be replace with MQTT sessions)
 - [x] Remove transport code (Javascript and Erlang)
 - [x] Remove postback, web socket and comet controller
 - [x] Move all wire, action and other JS-template code to new module `zotonic_mod_wires`
 - [x] Add MQTT web socket controller
 - [x] Remove / replace `#z_msg_v1{}` handling
 - [x] Integrate models into the topic tree
 - [x] Integrate models into API (replace API controller)
 - [x] Fixes and changes for legacy code (Pubzub, live, etc.)
 - [x] Check old MQTT topics and live topics (templates and erlang code)
 - [x] Handle form POST to topics, pass routing-id (for simple file uploads)
 - [x] Check the access control on model topics and routing topics
 - [x] Events for rsc model (`model/rsc/.../event/...`)
 - [x] Access control check for `m_email_status`
 - [x] Access control check for `m_facebook` graph calls
 - [x] Access control check for `m_survey`
 - [x] Timezone handling (client side timezone, user preferences)
 - [x] Language setting (client side language, user preferences)
 - [x] Propagate timezone / language changes to MQTT connection
 - [x] Add controller to post to topic tree (publish)
 - [x] Need to be able to set persistent id, for anonymous surveys
 - [x] OAuth tests and functionality (mod_oauth)
 - [x] Services: admin
 - [x] Services: zotonic_status - add model entry for status api calls
 - [x] Replace sites update in `zotonic_status` with model subscription
 - [x] Services: check if there are other calls in the js / templates
 - [x] Replace mod_backup download with resource `{% url api zotonic_http_accept="bert" star=["rsc", id] %}` (replacing with `{% url id zotonic_http_accept="application/x-bert" id=id %}`)
 - [x] Drop `persistent` table and references to it
 - [x] error messages on log on (need UI component or css)
 - [x] UI for password reminder and reset (prefer to use UI component)
 - [x] mod_signal: replace `{connect signal=....}` actions with MQTT topics (see `admin_log.tpl` and `admin_mailing_status.tpl`), also check for `mod_signal:emit` in Erlang code.

Known issues:

 - Handling of passwords that are `expired` and need a reset
 - On logon, the _rememberme_ checkbox is not handled
 - Race condition with in-flight MQTT messages when changing auth, and reconnect (seen with auth ui renders, might be resolved using retry on timeout or reconnect)
 - `mod_signup` *xprops* are broken (session thing, might need storage on client or passing using url)

Efficiency enhancements needed:

 - Caching of identity key lookups (now SQL query for each authenticated request)
 - Language lookups and fallbacks - use mochi static module

For another issue:

 - Add file upload code using MQTT (request uploader, send file in chunks via messages)
 - Add file upload by first requesting temp file, then http PUT to that file (using JS)
 - Add comet/post fallback for MQTT connection
 - Add SSE controller to stream from topic tree (subscribe)
 - Finalize `mod_oauth2` with UI and possibly *OAuth dance support*

### Checklist

- [ ] documentation updated
- [ ] tests added

### CODE REVIEW

**Comment by mmzeeman** [comment]
No context anymore... Render state sounds good for what it does.

**Comment by mworrell** [comment]
And... we have green https://travis-ci.org/zotonic/zotonic/builds/530429941

Now we have a couple of open issues:

 1. Docs need to be updated
 2. Known issues
 3. Broken stuff
 4. Efficiency enhancements

As these changes have been a long time in the pipeline, I propose to:

 1. Warn all users that we are going to update master
 2. Merge master
 3. Add issues for all outstanding things (see lists above)
 4. Start fixing on master with smaller merge requests

@mmzeeman, @ddeboer and @arjan are you ok with this?

**Comment by mworrell** [comment]
Email has been sent to zotonic-users and tweeted. Coming week we can press the merge button.

**Comment by arjan** [comment]
Congrats on the merge! :tada:

**Pull request merged**
