### PR TITLE
translation: add pt-br translation to all zotonic modules and skel

### PR DESCRIPTION
**Pull request by alvaropag**
The pt-br translation in this commit include all zotonic modules and the blog skel. In cases where existed pt.po files I updated them to pt-br content (they were pt-pt).
I wasn't able to generate updated pot files on master, something is broken inside mod_translation.

### CODE REVIEW

**Comment by mworrell** [comment]
As discussed in the mailinglist, see also issue #498

**Comment by mworrell** [comment]
As discussed in the mailinglist, see also issue #499

**Comment by ArthurClemens** [comment]
Working on that.

**Comment by alvaropag** [comment]
@ArthurClemens if I can help you in the development, please let me know.

**Comment by ArthurClemens** [comment]
See #1371

**Pull request closed without merging**
