### PR TITLE
Replace bash launcher scripts with erlscript

### PR DESCRIPTION
**Pull request by mworrell**
### Description

This replaces the bash scripts in zotonic_launcher with erlscript versions.

Continuation from #1765 by @ffringel

Preparation for issue #2189 by adding `config.d` subdirectory support to the launcher config handling. This is very rudimentary and will be further addressed in #2189.

(Rebased on master)

TODO:

- [x] Pass Travis tests
- [x] Fix distribution: long names vs short names
- [x] Support heart
- [x] Move bin/zotonic and bin/zotonic.erlscript to launcher app (minimal bin/zotonic script)
- [x] Remove old scripts
- [x] Initialization of `zotonic.config` and `erlang.config` on first run
- [x] Replace configuration `zotonic_sites_dir` and `zotonic_modules_dir` with `apps_user`, add env var `ZOTONIC_APPS` This fixes a build problem where the configs needed to be read by rebar before they were defined by (the compiled) zotonic.
- [x] Fix edocs build, which was broken since OTP-ification

For now unsupported: `addsite` command, this needs to be addressed in a separate issue, as it also concerns the site creation code in zotonic_site_status.

### Checklist

- [x] documentation updated
- [ ] tests added
- [ ] no BC breaks

### CODE REVIEW

**Comment by mworrell** [comment]
@ddeboer this works now, can you review the changes?

**Comment by mworrell** [comment]
@ffringel Thanks for starting this work!

**Comment by mworrell** [comment]
@seannaswell could you try build this branch on BSD? See if the new scripts work for you.

**Comment by seannaswell** [comment]
Setting up test environment, will confirm.

**Comment by seannaswell** [comment]
Okay, when compiling on FreeBSD all is well until Cotonic:

> ===> Compiling zotonic_mod_admin_config
===> Compiling zotonic_mod_email_status
===> Compiling zotonic_mod_base
> Installing cotonic from https://github.com/cotonic/cotonic.git
Cloning into 'cotonic'...
Done
make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 4: Need an operator
make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 13: Missing dependency operator
make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 43: Need an operator
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic
===> Hook for compile failed!

>gmake: *** [GNUmakefile:27: compile] Error 1
>[zotonic@zotonic ~/zotonic]$

**Comment by mworrell** [comment]
And if you patch cotonic like you did before? (that one is a separate issue we have to tackle)

BTW how are you testing?  Do you use a VM or do you have a BSD machine at hand?

**Comment by mworrell** [comment]
@seannaswell I made some changes to Cotonic, and now this branch seems to compile well on FreeBSD.

When running `bin/zotonic config` I did have an issue with `epmd` not being started.
Am not sure if that is an issue with my VM though.  The error was:

```
[test@cuppy /usr/home/test/zotonic]$ ./bin/zotonic configfile
=INFO REPORT==== 15-Oct-2019::13:55:37.524339 ===
Protocol 'inet_tcp': register/listen error: econnrefused
```

Manually starting epmd with `epmd -daemon` resolved this issue.

**Comment by mworrell** [comment]
Fixed the above problem by explicitly starting `epmd -daemon` before starting `net_kernel` in escript.

**Comment by seannaswell** [comment]
@mworrell  I setup a jail on my workstation (similar to Linux Containers), rather than testing on live server. Indeed it does compile correctly now. 

Will deploy a site locally for more testing, but if you setup a FreeBSD VM you are seeing the same thing I am. Nice to see Zotonic compile on FreeBSD without modifications...

**Comment by mworrell** [comment]
I am now running xhyve on macOS with FreeBSD 11.2 to try the compilation by hand. Regretfully Travis doesn't have FreeBSD as an available OS image.

**Pull request merged**
